apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 namespace: prod
 type: app
 app: nginx
spec:
 selector:
   matchLabels:
     type: app
     app: nginx
 replicas: 1
 template:
   metadata:
     labels:
       type: nginx
       app: nginx
   spec:
    containers:
    - name: container
      image: kaenga/nginx:latest
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m

